services:
  whoami:
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.125'
          memory: 256M
    image: kudaliar032/gitops-docker-swarm:v3
    ports:
    - 80
version: '3.8'
